language: python

python:
  - "3.7-dev"

# command to install dependencies
install:
  - pip install pipenv
  - pipenv install
  - pipenv run python setup.py develop
  - export FLASK_APP=frameapp.py

# command to run tests
script:
  - pipenv run py.test --disable-pytest-warnings -x tests/test_units.py


after_success:
	- pip install coveralls --upgrade 
	- coveralls


